### PR TITLE
Remove unused on top-level template statements

### LINKED ISSUE #626: RemoveUnusedTerms does not work on class/object
RemoveUnusedTerms does not produce a diff on stats:

```scala
class A {
  private val a = 1
}
object B {
  private val a = 1
}
package object C {
  private val a = 1
}
trait A {
  private val a = 1
}
```

### PR DESCRIPTION
**Pull request by gabro**
Fixes #626 

This is a workaround that tries to match by pos.start instead of full position.

I'm sure there are edge cases I haven't thought of, wdyt @olafurpg?

/cc @joan38

### CODE REVIEW

File: scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala [hunk 1]
```diff
@@ -53,8 +53,6 @@ class RemoveUnused(config: RemoveUnusedConfig)
         diagnostic.message.startsWith("local") &&
         diagnostic.message.endsWith("is never used")) {
         isUnusedTerm += diagnostic.position
-      } else {
-        () // ignore
```
Comment (gabro) [inline scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala]: this didn't seem to do much, so I've just removed it

**Comment by joan38** [comment]
Looks good to me

File: scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala (hunk 1 above)
Comment (olafurpg) [reply scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala]: It's was more for stylistic reasons but I don't feel strongly about it. I don't like having such a large `if else` without a closing `else`
