### PR TITLE
Fix #158, fix ExplicitReturnType for non-implicits

### LINKED ISSUE #158: Respect configuration in ExplicitReturnTypes
Following an offline chat with @dotta at Scala Italy, adding an explicit return type should be within the realm of the possible and it could greatly improve compile times.

```diff
-def foo(x: Int) = if (x > 3) Some(x) else None
+def foo(x: Int): Option[Int] = if (x > 3) Some(x) else None
```

This kind of mimics the idea of ExplicitImplicit.

@olafurpg do you see any blocker for this one?

### PR DESCRIPTION
**Pull request by taisukeoe**
This fixes #158 to add ExplicitReturnType with respecting configuration.

ATM memberKind and memberVisibility configuration supports are implemented in "AND" basis.

For example if you specify `[Val, Def]` for memberKind and `[Protected]` for memberVisibility, only `protected val` and `protected def`s are rewritten.
I believe it should be so, but please feel free to let me know if it's different from what you expect.

And I'm so sorry for making issue reference a bit dirty.

### CODE REVIEW

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala [hunk 1]
```diff
@@ -20,20 +23,40 @@ case class ExplicitReturnTypes(mirror: Mirror)
...
       else if (denot.isDef) denot.info.replaceFirst(".*\\)", "")
       else {
         throw new UnsupportedOperationException(
           s"Can't parse type for denotation $denot, denot.info=${denot.info}")
       }
-    base.parse[Type].toOption
+    if(denot.isVal || denot.isDef)
+      base.parse[Type].toOption
+    else
+      base.parse[Stat].toOption.flatMap{_.collect{case Term.Ascribe(_,typ) => typ}.headOption}
```
Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: This is added to extract a "argument" type from dennotation of Var like `var c_= (x$1 : Int):Unit`
I would appreciate it if you can suggest a smarter way!

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala [hunk 2]
```diff
@@ -20,18 +23,37 @@ case class ExplicitReturnTypes(mirror: Mirror)
 
   def defnName(defn: Defn): Option[Name] = Option(defn).collect {
     case Defn.Val(_, Seq(Pat.Var.Term(name)), _, _) => name
+    case Defn.Var(_, Seq(Pat.Var.Term(name)), _, _) => name
     case Defn.Def(_, name, _, _, _, _) => name
   }
 
+  def visibility(mod: Mod): Option[MemberVisibility] = Option(mod).flatMap {
```
Comment (gabro) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: You could use `collect` here and avoid the `wrapping` inside the `flatMap` as well as the fallback case.

```scala
Option(mod).collect {
  case _: Mod.Private => MemberVisibility.Private
  case _: ModProtected => MemberVisibility.Protected
}
```

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala [hunk 3]
```diff
@@ -20,18 +23,37 @@ case class ExplicitReturnTypes(mirror: Mirror)
...
+    case _: Mod.Private => Some(MemberVisibility.Private)
+    case _: Mod.Protected => Some(MemberVisibility.Protected)
+    case _ => None
+  }
+
+  def kind(defn: Defn): Option[MemberKind] = Option(defn).flatMap {
+    case _: Defn.Val => Some(MemberKind.Val)
```
Comment (gabro) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: same as above

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala (hunk 2 above)
Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: Fixed.
And changed `visibility` signature to be able to return `MemberVisibility.Public`.

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala (hunk 3 above)
Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: Fixed.

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala [hunk 4]
```diff
@@ -20,18 +22,39 @@ case class ExplicitReturnTypes(mirror: Mirror)
 
   def defnName(defn: Defn): Option[Name] = Option(defn).collect {
     case Defn.Val(_, Seq(Pat.Var.Term(name)), _, _) => name
+    case Defn.Var(_, Seq(Pat.Var.Term(name)), _, _) => name
     case Defn.Def(_, name, _, _, _, _) => name
   }
 
+  def visibility(mods: Traversable[Mod]): MemberVisibility =
+    mods
+      .collect {
```
Comment (olafurpg) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: `.collectFirst` == `.collect.headOption`

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala [hunk 5]
```diff
@@ -20,18 +22,39 @@ case class ExplicitReturnTypes(mirror: Mirror)
...
+        case _: Mod.Private => MemberVisibility.Private
+        case _: Mod.Protected => MemberVisibility.Protected
+      }
+      .headOption
+      .getOrElse(MemberVisibility.Public)
+
+  def kind(defn: Defn): Option[MemberKind] = Option(defn).collect {
+    case _: Defn.Val => MemberKind.Val
+    case _: Defn.Def => MemberKind.Def
+    case _: Defn.Var => MemberKind.Var
```
Comment (olafurpg) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: It seems we should make the `implicit` part configurable. I propose we include it under MemberKind, so that 
`explicitReturnTypes.memberKind = [Implicit]` means "insert explicit types for any implicit member, regardless if it's def/var/val. WDYT/

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala [hunk 6]
```diff
@@ -1,10 +1,12 @@
...
+import scala.collection.immutable.Seq
+import scala.meta._
+import scala.meta.contrib._
+import scalafix.config.{MemberKind, MemberVisibility}
 import scalafix.syntax._
-import scala.meta._, contrib._
 import scalafix.util.Whitespace
-import scala.collection.immutable.Seq
 
 // TODO: implement ExplicitReturnTypesConfig
```
Comment (olafurpg) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: No longer TODO :)

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala [hunk 7]
```diff
@@ -20,18 +22,39 @@ case class ExplicitReturnTypes(mirror: Mirror)
...
       else if (denot.isDef) denot.info.replaceFirst(".*\\)", "")
       else {
         throw new UnsupportedOperationException(
           s"Can't parse type for denotation $denot, denot.info=${denot.info}")
       }
-    base.parse[Type].toOption
+    if (denot.isVal || denot.isDef)
+      base.parse[Type].toOption
+    else
+      base.parse[Stat].toOption.flatMap {
```
Comment (olafurpg) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: Interesting, it seems the symbol for vars point to the setter. This may change in the future, FYI, but this solution is OK for now! We have tests :)

Can we use a for comprehension instead?

```scala
// NOTE: The symbol for vars points to the getter, this may change in the future
// but for now we parse the structure of the getter's denotation.  
for {
  stat <- base.parse[Stat].toOption
  typ <- stat.collectFirst { case Term.Ascribe(_, typ) => typ }
} yield typ
```

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala [hunk 8]
```diff
@@ -58,14 +82,27 @@ case class ExplicitReturnTypes(mirror: Mirror)
         typ <- defnType(defn)
       } yield ctx.addRight(replace, s": ${typ.treeSyntax}")
     }.to[Seq]
+
+    def checkModsScope(mods: Seq[Mod]): Boolean =
```
Comment (olafurpg) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: s/checkModsScope/matchesMemberVisibility/

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala [hunk 9]
```diff
@@ -58,14 +82,27 @@ case class ExplicitReturnTypes(mirror: Mirror)
...
+      ctx.config.explicitReturnTypes.memberVisibility
+        .contains(visibility(mods))
+
+    def checkDefnScope(defn: Defn): Boolean =
```
Comment (olafurpg) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: s/checkDefnScope/matchesMemberKind/

File: scalafix-tests/input/src/main/scala/test/ExplicitReturnTypes.scala [hunk 10]
```diff
@@ -1,9 +1,21 @@
...
+explicitReturnTypes.memberKind = [Def, Var]
+explicitReturnTypes.memberVisibility = [Public, Protected]
  */
 package test
 
 object ExplicitReturnTypes {
+  val a = 1
+  def b() = List
+  var c = true
+  protected val d = 1.0f
```
Comment (olafurpg) [inline scalafix-tests/input/src/main/scala/test/ExplicitReturnTypes.scala]: I think intellij-scala excludes cases when the right-hand side is a plain literal, see https://blog.jetbrains.com/scala/2016/10/05/beyond-code-style/

We could do something similar, have an option to skip the rewrite if the right-hand side body is a `Lit`.

```
explicitReturnTypes.skipSimpleDefinitions: Boolean // true by default
```

We can later expand on the heuristic to determine if a definition is "simple" or not.

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala (hunk 6 above)
Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: Thanks. Fixed.

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala (hunk 4 above)
Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: Fixed.

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala (hunk 5 above)
Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: I would think `Implicit` should not be an option and be always applied, since `Implicit` should always have explicit return type / type annotated even in Scala 2.x , like:
https://issues.scala-lang.org/browse/SI-9130

While I believe there is no use case that implicit should NOT have explicit return type, please let me know if there is.

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala (hunk 7 above)
Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: As you thought, `Var` part is the most tricky one in this PR.
While I didn't expect that `Var` denotation would be the setter function, do you think it's a bug in scala.meta? (If so, I'd love to contribute some to scala.meta :) )

ATM, I'll add some comments on this.

As for `for comprehension`, I fixed.

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala (hunk 8 above)
Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: Fixed.

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala (hunk 9 above)
Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: Fixed.

File: scalafix-tests/input/src/main/scala/test/ExplicitReturnTypes.scala (hunk 10 above)
Comment (taisukeoe) [inline scalafix-tests/input/src/main/scala/test/ExplicitReturnTypes.scala]: It's good idea to add `skipSimpleDefinitions` into ExplicitReturnType option. I added.

As you mentioned, we can revisit a definition of `simple` later on :)

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala [hunk 11]
```diff
@@ -20,18 +21,43 @@ case class ExplicitReturnTypes(mirror: Mirror)
...
         throw new UnsupportedOperationException(
           s"Can't parse type for denotation $denot, denot.info=${denot.info}")
       }
-    base.parse[Type].toOption
+    if (denot.isVal || denot.isDef)
+      base.parse[Type].toOption
+    else
+      /*
+      Currently a symbol of Var points to its setter function.
+      That's why its argument type should be extracted via pattern-match.
```
Comment (xeno-by) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: Let's point this to a getter. This would be a simple matter of changing https://github.com/scalameta/scalameta/blob/48eff97ac6951e5b58eb2ec7251f69d53a38a73a/scalahost/nsc/src/main/scala/scala/meta/internal/semantic/DenotationOps.scala#L15.

Would you consider contributing this to scalameta/scalameta?

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala [hunk 12]
```diff
@@ -58,14 +85,39 @@ case class ExplicitReturnTypes(mirror: Mirror)
...
+    import ctx.config.explicitReturnTypes._
+
+    def matchesMemberVisibility(mods: Seq[Mod]): Boolean =
+      memberVisibility.contains(visibility(mods))
+
+    def matchesMemberKind(defn: Defn): Boolean =
+      kind(defn).exists(memberKind.contains)
+
+    def matchesSimpleDefinition(rhs: Term): Boolean =
+      rhs.is[Lit] && skipSimpleDefinitions
```
Comment (xeno-by) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: What's a "simple definition"?

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala (hunk 11 above)
Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: Thanks for your confirmation and suggestion!
Yes, I'd love to. So can I file this issue, and try to solve it?

Comment (xeno-by) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: Yes. Please do :)

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala (hunk 12 above)
Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: With borrowing @olafurpg 's comment, I would define a "simple definition" as "its right-hand-side is a plain literal".

https://github.com/scalacenter/scalafix/pull/211/files/d49d74bbbb7eeece82e70af0df6f8b3ecf76d3f4#r121351776

I would also think a return type of a plain literal looks obvious, and needn't to be rewritten. What do you think about it?

Comment (xeno-by) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: At ScalaDays Copenhagen, I remember chatting with @olafurpg about binpacking in scalafmt, and he said that he had binpacking behaving differently for literals and non-literals. Afterwards, the special behavior for literals ended up being so useful that Olaf upgraded it from just literals to literals and short identifiers.

When I saw a notion of a "simple definition" in this pull request, I thought that maybe that scalafmt story and this pull request relate in any way. Could you comment on that? /cc @olafurpg

Comment (olafurpg) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: I'd say in this case we want to treat identifiers as "complex definitions" since inferring their type may require inferring complex definitions

```scala
def foo = Generic[Bar] // infers to complex type `String :+: Int :+ ... :+: HNil`
implicit val x  = foo // not simple, we want explicit type here.
```

I think literals are a good enough for "simple definitions", at least to start with. We may later want to handle more sophisticated cases like

```
val foo = Option.empty[Int]
// after rewrite
val foo: Option[Int] = None
```

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala [hunk 13]
```diff
@@ -58,14 +85,39 @@ case class ExplicitReturnTypes(mirror: Mirror)
...
+
     tree
       .collect {
         case t @ Defn.Val(mods, _, None, body)
-            if t.hasMod(mod"implicit") &&
-              !isImplicitly(body) =>
+            if t.hasMod(mod"implicit") && !isImplicitly(body)
+              || !matchesSimpleDefinition(body)
```
Comment (olafurpg) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: Seems like this complex condition is repeated for val/var/def. Can we extract it into a helper? Something like

```scala
def isRewriteCandidate(t: Defn, mods: Seq[Mod], body: Term): Boolean = ???
```

Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: Indeed.
I have extracted it into a helper function, and happen to find that `implicit var` was not include in rewrite scope. I believe it should be, and have applied the same helper function into `Var` as `Val` or `Def`.

Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: Like:

```scala
private implicit var j = 1

//after rewrite

private implicit var j: Int = 1
```

File: scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala (hunk 12 above)
Comment (taisukeoe) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: As @xeno-by suggested, it seems to be hard to guess "what is simple?".
So now I think `skipDefinitionsByLiteral` would be a more right word than `skipSimpleDefinitions` ATM.
Of course I'm open to revisit the name after we expand the definition of "simple".

Comment (olafurpg) [inline scalafix-core/src/main/scala/scalafix/rewrite/ExplicitReturnTypes.scala]: I think I prefer to have the flexibility to redefine simple in future releases. We could make the option an enum, `skipDefinitions = literals/simple`, but I think that's overkill for now. Let's keep it `skipSimpleDefinitions`.

**Comment by taisukeoe** [comment]
Thanks!
