### PR TITLE
Several fixes

### LINKED ISSUE #788: Expose version numbers via resources in scalafix-interfaces
It would be helpful to have a property files in resources of the scalafix-interfaces module. This would allow sbt-scalafix to depend on scalafix-interfaces and find the latest scalafix version

### LINKED ISSUE #817: Allow semantic rules to require specific scalacOptions
Some rules like `RemoveUnusedImports` require -Ywarn-unused-imports to function. It would be good if those rules could document that they require a particular scalac setting in order to function. In case the setting is not enabled, then scalafix should fail at the start with an error message saying what setting is required.

### LINKED ISSUE #821: Expose available rule names in scalafix-interfaces
scalafix-interfaces should expose a method to get a `List[String]` of valid rules names. This list should include rules that are loaded via service loaders. This list can be used by sbt-scalafix to provide completions from the sbt shell.

### PR DESCRIPTION
**Pull request by olafurpg**
See independent commits. Travis CI was freezing for a couple hours so I couldn't open separate PRs for each fix.

Fixes #821
Fixes #817
Fixes #788

### CODE REVIEW

File: scalafix-core/src/main/scala/scalafix/internal/v1/Rules.scala [hunk 1]
```diff
@@ -71,35 +68,15 @@ case class Rules(rules: List[Rule] = Nil) {
...
-      val name = fn(v0.SemanticdbIndex.empty).name
-      new LegacySemanticRule(name, fn)
-    }
+  def all(classLoader: ClassLoader): List[Rule] = {
+    import scala.collection.JavaConverters._
+    ServiceLoader
+      .load(classOf[Rule], classLoader)
+      .iterator()
+      .asScala
+      .toList
```
Comment (gabro) [inline scalafix-core/src/main/scala/scalafix/internal/v1/Rules.scala]: beautiful 😍

File: scalafix-core/src/main/scala/scalafix/rule/RuleName.scala [hunk 2]
```diff
@@ -25,7 +25,7 @@ final case class RuleName(identifiers: List[RuleIdentifier]) {
   def value: String =
     if (isDeprecated) identifiers.mkString("+")
     else if (nonDeprecated.isEmpty) "empty"
-    else nonDeprecated.mkString("+")
+    else nonDeprecated.head.value
```
Comment (gabro) [inline scalafix-core/src/main/scala/scalafix/rule/RuleName.scala]: If you feel like

```scala
if (isDeprecated) identifiers.mkString("+")
else nonDeprecated.headOption.map(_.value).getOrElse("empty")
```

Comment (olafurpg) [reply scalafix-core/src/main/scala/scalafix/rule/RuleName.scala]: Refactored into pattern match to avoid `head` ;)
