### PR TITLE
Fix #298

### LINKED ISSUE #298: Fail fast on wrong sourceroot
Currently, if you pass in a wrong sourceroot then the inputs then some files to be fixed may not have semantic information. Scalafix will still continue to run semantic rewrites, which get no lookup matches in SemanticCtx, perform no diff, and scalafix exits with code 0, OK. 

Scalafix should fail fast if a file to be fixed has no associated semantic information.

### PR DESCRIPTION
**Pull request by olafurpg**

### CODE REVIEW

File: scalafix-tests/unit/src/test/scala/scalafix/cli/CliSemanticTest.scala [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+    name = "--sourceroot points to non-existing file",
+    args = Seq(
+      "--sourceroot",
+      CommonOptions.default.workingDirectory,
+      "--classpath",
+      BuildInfo.semanticClasspath.getAbsolutePath
+    ),
+    expectedExit = ExitStatus.InvalidCommandLineOption,
+    outputAssert = msg => {
+      assert(msg.contains("is not a file"))
```
Comment (olafurpg) [inline scalafix-tests/unit/src/test/scala/scalafix/cli/CliSemanticTest.scala]: cc/ @usrinivasan scalafix-cli will now fail fast when the --sourceroot maps semanticdb relative paths to non-existing files

File: scalafix-tests/unit/src/test/scala/scalafix/cli/CliSemanticTest.scala [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+        .resolve("input")
+        .resolve("src")
+        .resolve("main")
+        .toString(),
+      "--classpath",
+      BuildInfo.semanticClasspath.getAbsolutePath
+    ),
+    expectedExit = ExitStatus.InvalidCommandLineOption,
+    outputAssert = msg => {
+      assert(msg.contains("No semanticdb associated with"))
```
Comment (olafurpg) [inline scalafix-tests/unit/src/test/scala/scalafix/cli/CliSemanticTest.scala]: cc/ @usrinivasan Here the --sourceroot maps to existing files but there exist files that are supposed to get fixed but have no associated .semanticdb files.

**Comment by olafurpg** [comment]
I will go ahead and merge this to publish a new milestone release. I am happy to iterate further on the contents of the error messages to make them clearer.
