### PR TITLE
Fix #493, handle synthetics and symbol signatures in Disable.

### LINKED ISSUE #493: Disable reports errors on symbol signatures
I want to disable usage of some class `Foo`, so I write 
```
rule = Disable
Disable.symbols = [mypackage.Tests.Foo]
```
and corresponding test
```
package mypackage

object Tests {
  class Foo
  class Bar extends Foo // assert: Disable.Foo
}
```

But that test throws a strange error 
```
_root_.mypackage.Tests.Foo#`<init>`()V.:1: error: [Disable.Foo] Foo is disabled
(): Foo
    ^
```
that's impossible to catch.

### PR DESCRIPTION
**Pull request by olafurpg**
Previously, Disable reported an error on the positions of any
ResolvedName to a disabled symbol, including Input.Synthetic and
Input.Denotation which are invisible and don't appear in the source
file. Now Disable ignores symbol signatures and for synthetics it
points a caret at the position where the synthetic got expanded
and includes the pretty-printed representation of the synthetic
to help make sense of the error message.

Review @vovapolu

### CODE REVIEW

File: scalafix-core/shared/src/main/scala/scalafix/internal/rule/Disable.scala [hunk 1]
```diff
@@ -30,21 +30,34 @@ final case class Disable(index: SemanticdbIndex, config: DisableConfig)
       .getOrElse("disable", "Disable")(DisableConfig.default)
       .map(Disable(index, _))
 
-  override def check(ctx: RuleCtx): Seq[LintMessage] =
-    ctx.index.names.collect {
+  override def check(ctx: RuleCtx): Seq[LintMessage] = {
+    val buffer = List.newBuilder[LintMessage]
```
Comment (vovapolu) [inline scalafix-core/shared/src/main/scala/scalafix/internal/rule/Disable.scala]: Maybe make it immutable with `Option[LintMessage]` and `.flatMap`? Or performance is important here?

File: scalafix-tests/input/src/main/scala/test/Disable.scala [hunk 2]
```diff
@@ -52,4 +56,10 @@ If you must Option.get, wrap the code block with
 ...
 // scalafix:on Option.get
 */
-}
\ No newline at end of file
+  val l: ListBuffer[Int] =
+    scala.collection.mutable.ListBuffer.empty[Int] // scalafix:ok Disable.ListBuffer
```
Comment (vovapolu) [inline scalafix-tests/input/src/main/scala/test/Disable.scala]: :thinking: why is it ok?

File: scalafix-core/shared/src/main/scala/scalafix/internal/rule/Disable.scala (hunk 1 above)
Comment (olafurpg) [reply scalafix-core/shared/src/main/scala/scalafix/internal/rule/Disable.scala]: Refactored to avoid builder.

File: scalafix-tests/input/src/main/scala/test/Disable.scala (hunk 2 above)
Comment (olafurpg) [reply scalafix-tests/input/src/main/scala/test/Disable.scala]: `// scalafix:ok` is about the same as `// assert: `, since scalafix will report an error on `// scalafix:ok` if it's not used. Maybe we should consider removing `// scalafix: assert` 🤔 but assert also has the option to test the exact error message.

File: scalafix-tests/input/src/main/scala/test/Disable.scala [hunk 3]
```diff
@@ -52,4 +56,9 @@ If you must Option.get, wrap the code block with
 ...
 // scalafix:on Option.get
 */
-}
\ No newline at end of file
+  val l: ListBuffer[Int] = scala.collection.mutable.ListBuffer.empty[Int] // assert: Disable.ListBuffer
+  List(1) + "any2stringadd" /* assert: Disable.any2stringadd
+  ^
+any2stringadd is disabled and it got inferred as `scala.Predef.any2stringadd[List[Int]](*)`
+  */
```
Comment (MasseGuillaume) [inline scalafix-tests/input/src/main/scala/test/Disable.scala]: so multiline asserts are useful after all ;-).

File: scalafix-tests/input/src/main/scala/test/Disable.scala [hunk 4]
```diff
@@ -52,4 +56,9 @@ If you must Option.get, wrap the code block with
 ...
 // scalafix:on Option.get
 */
-}
\ No newline at end of file
+  val l: ListBuffer[Int] = scala.collection.mutable.ListBuffer.empty[Int] // assert: Disable.ListBuffer
+  List(1) + "any2stringadd" /* assert: Disable.any2stringadd
+  ^
+any2stringadd is disabled and it got inferred as `scala.Predef.any2stringadd[List[Int]](*)`
```
Comment (MasseGuillaume) [inline scalafix-tests/input/src/main/scala/test/Disable.scala]: Not blocking, but I don't think this is the most meaningful example.
