### PR TITLE
Fix legacy sythetics (fix #795)

### LINKED ISSUE #795: v0 Sythetics cannot parse.
Here is what I get:

```scala
*(canBuildFrom[IntInt, ])
*[Vector[Int]Tuple2[IntInt, ], Map[IntInt, ], ]
*[Seq[Int]Tuple2[IntInt, ], Map[IntInt, ], ]
```

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

File: scalafix-core/src/main/scala/scalafix/internal/v0/LegacyCodePrinter.scala [hunk 1]
```diff
@@ -30,12 +31,12 @@ class LegacyCodePrinter() {
       text.append(start)
       var first = true
       trees.foreach { tree =>
-        fn(tree)
```
Comment (MasseGuillaume) [inline scalafix-core/src/main/scala/scalafix/internal/v0/LegacyCodePrinter.scala]: This was the bug.
